backend:
  name: github
  repo: bsubedi26/gulp-jekyll

media_folder: assets
public_folder: assets

publish_mode: editorial_workflow

collections:
  - name: gulper
    label: project
    folder: fold
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { name: image, label: Header Image, widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
