backend:
  name: github
  repo: bsubedi26/gulp-jekyll
  branch: master
  site_domain: stoic-goodall-65465c.netlify.com

media_folder: assets

publish_mode: editorial_workflow

collections:
  - name: "page" # Used in routes, e.g. /admin/collections/blog
    label: "Page" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Layout"
        name: "layout"
        widget: "select"
        options: ["post", "default"]
        default: "post"

      - label: "Align Content"
        name: "align"
        widget: "select"
        options: ["left", "center", "right"]
      


      - {
        label: "Section",
        name: "section",
        widget: "relation",
        collection: "sections",
        searchFields: ["title"],
        valueField: "title",
      }
      - {
          label: "Subsection",
          name: "subsection",
          widget: "relation",
          collection: "subsections",
          searchFields: ["title"],
          valueField: "slug",
          filterField: "section"
        }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

      - name: "sections"
        label: "Sections"
        folder: "sections"
        create: true
        slug: "{{slug}}"
        fields:
          - {label: "Section name", name: "title", widget: "string"}

      - name: "subsections"
        label: "Subsections"
        folder: "subsections"
        create: true
        slug: "{{slug}}"
        fields:
          - {
              label: "Section",
              name: "section",
              widget: "relation",
              collection: "sections",
              searchFields: ["title"],
              valueField: "title"
            }
          - {label: "Subsection name", name: "title", widget: "string"}